version: '3'
services:
    mattermost:
        # This can be updated with docker tags from https://hub.docker.com/r/mattermost/mattermost-enterprise-edition/tags
        image: mattermost/mattermost-enterprise-edition:master.227937

        ports:
            - "8065:8065"
        environment:
            - MM_SERVICESETTINGS_SITEURL # Gitpod init script will set this

            - MM_SQLSETTINGS_DRIVERNAME=postgres
            - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mostest@db/mattermost_test?sslmode=disable
            - MM_SERVICESETTINGS_LISTENADDRESS=:8065
            - MM_SERVICESETTINGS_ENABLEBOTACCOUNTCREATION=true
            - MM_SERVICESETTINGS_ENABLEOAUTHSERVICEPROVIDER=true
            - MM_SERVICESETTINGS_ENABLEDEVELOPER=true
            - MM_SERVICESETTINGS_ENABLETESTING=true
            - MM_PLUGINSETTINGS_AUTOMATICPREPACKAGEDPLUGINS=true
            - MM_PLUGINSETTINGS_ENABLEUPLOADS=true
            - MM_FEATUREFLAGS_AppsEnabled=true

            - MM_LOGSETTINGS_CONSOLELEVEL=DEBUG
            - MM_LOGSETTINGS_FILELEVEL=DEBUG

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: mostest
            POSTGRES_USER: mmuser
            POSTGRES_DB: mattermost_test
